apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-config-override
  namespace: rook
data:
  config: |
    [global]
    rbd default features = 1
---
apiVersion: rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook
  namespace: rook
spec:
  dataDirHostPath: /var/lib/rook
  dashboard:
    enabled: true
  storage:
    useAllNodes: true
    useAllDevices: false
    config:
      databaseSizeMB: "1024"
      journalSizeMB: "1024"
---
apiVersion: rook.io/v1alpha1
kind: Pool
metadata:
  name: velox
  namespace: rook
spec:
  replicated:
    size: 2
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  name: rook-block
parameters:
  clusterName: rook
  fstype: ext4
  pool: velox
provisioner: rook.io/block
reclaimPolicy: Delete
